### ISSUE TITLE
Sequencing multiple portals doesn't work

### ISSUE THREAD

**Issue by moroshko** [alex-cory/react-useportal#2]
I'm trying to achieve the following:

1. Button is clicked to open the first modal.
2. In this modal, there is another button. When clicked, it should close the (first) modal, and open a second modal.

The first modal is closed as expected, but the second modal is not opened. Its `isOpen` is always `false`.

Repro: [Codesandbox](https://codesandbox.io/s/yq30k343xv)

**Comment by alex-cory** [comment]
I will fix this tonight, but for now you can pass the synthetic event from `onClick` to each.
![image](https://user-images.githubusercontent.com/5455859/57340538-14cb3d00-70eb-11e9-8fb4-00fb320f47d6.png)

**Comment by alex-cory** [comment]
Here's your specific use case https://codesandbox.io/s/6wlv9990p3

**Comment by alex-cory** [comment]
Apologies for the delay on the dependencies problem. After porting to typescript, I removed all dependencies :)
![](https://media1.giphy.com/media/90F8aUepslB84/giphy.gif)
