### ISSUE TITLE
Cannot resolve dependency with react@17.0.2

### ISSUE THREAD

**Issue by joniaiuser** [alex-cory/react-useportal#72]
**Describe the bug**
`npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from react-useportal@1.0.14`

**Comment by liuyisnake** [comment]
peer dependency updated but seems not publish to npm respository

**Comment by poacher2k** [comment]
@alex-cory : It would be really appreciated if you had the time to release a new version to NPM :)

**Comment by alex-cory** [comment]
Published
