### ISSUE TITLE
Warnings when using react-useportal with React 18.x - Plans for updating peerDeps?

### ISSUE THREAD

**Issue by nitelite** [alex-cory/react-useportal#81]
I have a sizable project where I used react-useportal in a few places, and now I am working on upgrading it from running React 17.9 to React 18.2.

Are there any plans for verifying this package's functionality on React 18.x and adding the version to the peerDependencies? Right now I am getting some warnings etc about missing peerDependencies because my React version is "too new".

**Comment by shestakov-vladyslav** [comment]
Yes, please make it compatible with React v18
![image](https://user-images.githubusercontent.com/18069756/181266607-88f289fd-9e90-45e9-ab48-3cb4371e992e.png)

**Comment by huwshimi** [comment]
I've submitted a PR for this: https://github.com/alex-cory/react-useportal/pull/84.
